resultStr = {'wpli_debiased_delta.mat',...
    'wpli_debiased_theta.mat', ...
    'wpli_debiased_alpha1.mat', ...
    'wpli_debiased_alpha2.mat', ...
    'wpli_debiased_beta.mat', ...
    'wpli_debiased_gamma.mat', ...
    'wpli_debiased_alphaTheta.mat'};

figureStr = { ...
    'plotConnDist'};
% {'conMatrices', ...
%     'R_corrCorrMatrix', ...
%     'scatterGrpAvg', ...
%     'plotGrpAvg', ...
%     'plotConnDist', ...
%     'plotUnitwiseDist'};

for i = 1:length(resultStr)
    disp(resultStr{i})
    fprintf('\t loading ... ')
    load(resultStr{i})
    fprintf('done! \n')
    
    for iFig = 1:length(figureStr)
        currFigStr = figureStr{iFig};
        bv_plotResults(resultStr{i}, currFigStr, 1)
    end
end
