resultStr = {'pli_delta.mat', ...
    'pli_theta.mat',...
    'pli_alpha1.mat',...
    'pli_alpha2.mat',...
    'pli_beta.mat',...
    'pli_gamma.mat'};
%     'wpli_debiased_delta.mat',...
%     'wpli_debiased_theta.mat',...
%     'wpli_debiased_alpha1.mat',...
%     'wpli_debiased_alpha2.mat',....
%     'wpli_debiased_beta.mat',...
%     'wpli_debiased_gamma.mat'};

% figureStr = {'conMatrices', ...
%     'R_corrCorrMatrix', ...
%     'scatterGrpAvg', ...
%     'plotGrpAvg', ...
%     'plotConnDist', ...
%     'plotUnitwiseDist'...
%     'degreeTopoplot'};

figureStr = {'degreeTopoplot'};

for i = 1:length(resultStr)

    switch(figureStr{1})
        case {'conMatrices', ...
                'R_corrCorrMatrix', ...
                'scatterGrpAvg', ...
                'plotGrpAvg', ...
                'plotConnDist', ...
                'plotUnitwiseDist'...
                'degreeTopoplot',...
                'ccTopoplot'} ;
    
            for iFig = 1:length(figureStr)
                currFigStr = figureStr{iFig};
                bv_plotResults(resultStr{i}, currFigStr, 1)
            end
            
        case 'barPlotGlobConn'
            
            disp(resultStr{i})
            fprintf('\t loading ... ')
            load(resultStr{i})
            fprintf('done! \n')
            
            globConn(i) = results.r_scanwise;
            
        case 'barUnitWiseConn'
            t
            disp(resultStr{i})
            fprintf('\t loading ... ')
            load(resultStr{i})
            fprintf('done! \n')
            
            unitWiseConn(i) = results.mr_unitwise;
            unitWise75Conn(i) = results.mr_unitwise75;
    end
            
    
end
